# NumPy

In [3]:
import numpy as np

1) Write a NumPy program to test whether none of the elements of a given array is zero.

In [37]:
b = np.array([1,2,0,3,4])

def checkzeros(a):
    for i in a:
        if i == 0:
            print('i = ',i,'This element equal zero')

        else:
            print('i = ',i,"This element not equal zero")

            
checkzeros(b)

i =  1 This element not equal zero
i =  2 This element not equal zero
i =  0 This element equal zero
i =  3 This element not equal zero
i =  4 This element not equal zero


2) Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [4]:
b = np.array([1,2,0,3,4])

def checkzeros(a):
    for i in a:
        if i == 1:
            print('i = ',i,'This element equal one')

        else:
            print('i = ',i,"This element not equal one")

            
checkzeros(b)

i =  1 This element equal one
i =  2 This element not equal one
i =  0 This element not equal one
i =  3 This element not equal one
i =  4 This element not equal one


3) Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [23]:
equalwzottol = np.array([4,23,2001,11,22,2000.0002])
equlwiztol = np.array([4,23.0003,2001,11,22,2000.0002])

#compare between two arrays if the qual to each other get TRUE if not get FALSE
print("equal:")
print(np.equal(equalwzottol, equlwiztol))

#absolute(arr1 - arr2) <= (array1 + array2 * absolute(arr2)) get TRUE
print("equal within a tolerance:")
print(np.allclose(equalwzottol, equlwiztol))

equal:
[ True False  True  True  True  True]
equal within a tolerance:
False


4) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [9]:
arrzeros=np.zeros(10)
print("An array of 10 zeros:",arrzeros)
print()
arrones=np.ones(10)
print("An array of 10 ones:",arrones)
print()
arrfivz=np.ones(10)*5
print("An array of 10 fives:",arrfivz)

arrs = arrzeros,arrones,arrfivz
arrs

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]))

5) Write a NumPy program to create an array of the integers from 30 to70.

In [107]:
arrayy = np.array([range(30,71)])
print('array00 = \n',arrayy)

print()

arrayyy = np.arange(30,71)
print('array00 = \n',arrayyy)

array00 = 
 [[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
  54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]]

array00 = 
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


6) Write a NumPy program to create a 3x3 identity matrix

In [54]:
mat = np.identity(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7) Write a NumPy program to generate a random number between 0 and 1

In [70]:
randzero2one = np.random.rand(1,1)
print(randzero2one)

array([[0.25627968]])

8) Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [71]:
randnosndistrib = np.random.normal(0,1,15)
randnosndistrib

array([-0.01575811, -0.70622156, -0.17523487,  0.41530617, -1.17183244,
       -1.35135609,  1.10027569, -0.28602457,  0.32957299, -0.9346542 ,
       -0.30592478, -0.06174393, -0.85357541,  1.26015853,  0.13179487])

9) Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [96]:
vectt01 = np.arange(15,56)
v01 = len(vectt01)-1
vectt01[1:v]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

10) Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [134]:
artbintg =np.arange(0,10,2)
artbintg

artbintg1 = np.random.randint(1,11,5)
artbintg1

array([2, 2, 4, 8, 7])

11) Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [144]:
from numpy import matlib
np.matlib

matrixx = matlib.ones((10,10),dtype = 'int')

matrixx[1:-1, 1:-1] = 0

matrixx

matrix([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

12) Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [163]:
# 1st method

matrixz = matlib.zeros((5,5),dtype = 'int')
matrixz[0,0] = 1
matrixz[1,1] = 2
matrixz[2,2] = 3
matrixz[3,3] = 4
matrixz[4,4] = 5

matrixz


# 2nd method

matrixz01 = np.diag([1, 2, 3, 4, 5])

print(matrixz01)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


13) Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [166]:
matxx= np.zeros((4, 4))
matxx[::2, 1::2] = 1
matxx[1::2, ::2] = 1
matxx

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

16) Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [40]:
arrayn = np.array([[1,2,3],[4,5,6],[7,8,9]])
n = 5
len(arrayn)
def lessgreater(a):
    for i in a:
        print('numbers greater than a specified number (n) \n',i[i>=n]) 
#         print(i[1] >= n) that print true or false if number in columns greater than or equal (n)
        print('--------------------------------------------')
        print('numbers less than a specified number (n) \n',i[i<=n])

        
lessgreater(arrayn)
# print(arrayn.all()) #to check if it can iterable or not, if it True so it is iterable

numbers greater than a specified number (n) 
 []
--------------------------------------------
numbers less than a specified number (n) 
 [1 2 3]
numbers greater than a specified number (n) 
 [5 6]
--------------------------------------------
numbers less than a specified number (n) 
 [4 5]
numbers greater than a specified number (n) 
 [7 8 9]
--------------------------------------------
numbers less than a specified number (n) 
 []


**SORRY FOR NO COMMENTS BUT I WILL TRY UPDATED IT WITH COMMENTS TO EXPLAIN ANY LINE CODE**


**THANK YOU ❤️**